fix: return unformatted if object
xeroxinteractive/fractal-theme pull request #63
Opened 2020-04-22 16:19 UTC by tinytim84

2020-04-22 17:43 UTC, AndrewLeedham requested changes
The prettier implementation does not need to change, but it expects a string. The problem is here: https://github.com/xeroxinteractive/fractal-theme/blob/dev/views/partials/browser/panel-context.nunj#L14 prettier is running before format, but format is the filter that converts it to a string, they need reversing. Also while you are in there, prettier should be added to the non-collated part: https://github.com/xeroxinteractive/fractal-theme/blob/dev/views/partials/browser/panel-context.nunj#L5

2020-05-04 17:02 UTC, tinytim84 commented
This should be ready for review now, there are still some test bugs in the corresponding [framework PR](https://github.com/xeroxinteractive/xerox-framework/pull/1520), but this one is ready to be reviewed while I fix those.

2020-05-05 09:48 UTC, AndrewLeedham commented
The text seems to move when clicking between them can that be removed? Seems to be because neither is selected during loading, I think 1 should always be selected and the contents should have a loading animation.

Also the 0.6 transparency for the loading state looks strange when it loads so quick. There is already a loading animation for when a component is rendering on the server can we use that if the Ajax call takes more than 100ms, otherwise just swap straight away?

![Fractal Theme Jumpyness](https://user-images.githubusercontent.com/5557458/81053348-d82c5000-8ebc-11ea-947e-7df3da9ef3e3.gif)

2020-05-05 10:00 UTC, AndrewLeedham requested changes
The text seems to move when clicking between them can that be removed? Seems to be because neither is selected during loading, I think 1 should always be selected and the contents should have a loading animation.

Also the 0.6 transparency for the loading state looks strange when it loads so quick. There is already a loading animation for when a component is rendering on the server can we use that if the Ajax call takes more than 100ms, otherwise just swap straight away?

![Fractal Theme Jumpyness](https://user-images.githubusercontent.com/5557458/81053348-d82c5000-8ebc-11ea-947e-7df3da9ef3e3.gif)

2020-05-05 15:25 UTC, tinytim84 commented
> The text seems to move when clicking between them can that be removed? Seems to be because neither is selected during loading, I think 1 should always be selected and the contents should have a loading animation.
> 
> Also the 0.6 transparency for the loading state looks strange when it loads so quick. There is already a loading animation for when a component is rendering on the server can we use that if the Ajax call takes more than 100ms, otherwise just swap straight away?
> 
> ![Fractal Theme Jumpyness](https://user-images.githubusercontent.com/5557458/81053348-d82c5000-8ebc-11ea-947e-7df3da9ef3e3.gif)

I've done these updates.  Your machine must be much faster than mine, I never have that short a delay between changing variants!

2020-05-05 16:26 UTC, AndrewLeedham requested changes
The tabs look odd when stacked, perhaps it should be horizontally scrollable?
![image](https://user-images.githubusercontent.com/5557458/81090286-66242d00-8ef5-11ea-9b3b-851605592a63.png)

2020-05-05 16:26 UTC, AndrewLeedham commented on assets/js/theme.js
> +function logState(currentComponent, url, replace = false) {
Not sure log is the right word here?

2020-05-05 17:11 UTC, tinytim84 commented
> The tabs look odd when stacked, perhaps it should be horizontally scrollable?
> ![image](https://user-images.githubusercontent.com/5557458/81090286-66242d00-8ef5-11ea-9b3b-851605592a63.png)

Will it not look strange with a scrollbar underneath it too?  Maybe arrows to the right and left?

2020-05-05 17:18 UTC, AndrewLeedham commented
> > The tabs look odd when stacked, perhaps it should be horizontally scrollable?
> > ![image](https://user-images.githubusercontent.com/5557458/81090286-66242d00-8ef5-11ea-9b3b-851605592a63.png)
> 
> Will it not look strange with a scrollbar underneath it too? Maybe arrows to the right and left?

If you use `overflow-x: auto;` it should be a transparent scrollbar that is what happens with the current framework header bar thingy

2020-05-06 10:33 UTC, AndrewLeedham requested changes
Looks good but did something change with the border on the bottom? They are not bleeding into the content anymore: 
![image](https://user-images.githubusercontent.com/5557458/81167589-5d7f3580-8f8d-11ea-9af1-872c2641670f.png)

2020-05-06 11:07 UTC, tinytim84 commented
> Looks good but did something change with the border on the bottom? They are not bleeding into the content anymore:
> ![image](https://user-images.githubusercontent.com/5557458/81167589-5d7f3580-8f8d-11ea-9af1-872c2641670f.png)

It's the scrollbar.  It's almost exactly the same grey as the outline.  If it's not there they still bleed in.

2020-05-06 11:33 UTC, AndrewLeedham commented
> It's the scrollbar. It's almost exactly the same grey as the outline. If it's not there they still bleed in.

:( ok lets leave it as this for now, perhaps in the future we can implement something like https://material-ui.com/components/tabs/#automatic-scroll-buttons

2020-05-06 11:33 UTC, AndrewLeedham submitted a review, later dismissed

2020-05-07 15:45 UTC, AndrewLeedham requested changes
Ajax seems somewhat pointless now the tabs disappear while loading. I would say either just use normal links and don't bother with Ajax, or have the loading animation in both the details at the bottom and the display iframe, so the tabs are always visible.

2020-05-07 20:06 UTC, tinytim84 commented
> Ajax seems somewhat pointless now the tabs disappear while loading. I would say either just use normal links and don't bother with Ajax, or have the loading animation in both the details at the bottom and the display iframe, so the tabs are always visible.

That's a fair point.  I've fixed it in the latest changes.

2020-05-11 09:43 UTC, AndrewLeedham commented
LGTM

2020-05-11 09:43 UTC, AndrewLeedham approved these changes

2020-05-11 09:44 UTC, merged